(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Expect_DHInit
  |`Expect_Exec_Success
  |`Expect_GexInit
  |`Expect_Pty_Success
  |`Expect_Shell_Success
  |`Notify_Auth_Permanent_Failure
  |`Receive_Auth_Banner
  |`Receive_Auth_ChangeReq
  |`Receive_Auth_Failure
  |`Receive_Auth_PublicKey_OK
  |`Receive_Auth_Req_Host
  |`Receive_Auth_Req_None
  |`Receive_Auth_Req_Password_Change
  |`Receive_Auth_Req_Password_Request
  |`Receive_Auth_Req_PublicKey_Check
  |`Receive_Auth_Req_PublicKey_Request
  |`Receive_Auth_Success
  |`Receive_Channel_Close
  |`Receive_Channel_Data
  |`Receive_Channel_EOF
  |`Receive_Channel_ExtendedData
  |`Receive_Channel_Failure
  |`Receive_Channel_GlobalRequest_CancelTCPForward
  |`Receive_Channel_GlobalRequest_TCPForward
  |`Receive_Channel_OpenConfirmation
  |`Receive_Channel_OpenFailure
  |`Receive_Channel_Open_DirectTCP
  |`Receive_Channel_Open_Session
  |`Receive_Channel_Open_TCPForward
  |`Receive_Channel_Open_X11
  |`Receive_Channel_RequestFailure
  |`Receive_Channel_RequestSuccess
  |`Receive_Channel_RequestSuccessPort
  |`Receive_Channel_Request_Env
  |`Receive_Channel_Request_Exec
  |`Receive_Channel_Request_ExitSignal
  |`Receive_Channel_Request_ExitStatus
  |`Receive_Channel_Request_LocalFlowControl
  |`Receive_Channel_Request_Pty
  |`Receive_Channel_Request_Shell
  |`Receive_Channel_Request_Signal
  |`Receive_Channel_Request_Subsystem
  |`Receive_Channel_Request_WindowChange
  |`Receive_Channel_Request_X11
  |`Receive_Channel_Success
  |`Receive_Channel_WindowAdjust
  |`Receive_Dhgexsha1_Group
  |`Receive_Dhgexsha1_Init
  |`Receive_Dhgexsha1_Reply
  |`Receive_Dhgexsha1_Request
  |`Receive_Dhgroupsha1_Init
  |`Receive_Dhgroupsha1_Reply
  |`Receive_Transport_Debug
  |`Receive_Transport_Disconnect
  |`Receive_Transport_Ignore
  |`Receive_Transport_KexInit
  |`Receive_Transport_NewKeys
  |`Receive_Transport_ServiceAccept_Connection
  |`Receive_Transport_ServiceAccept_UserAuth
  |`Receive_Transport_ServiceReq_Connection
  |`Receive_Transport_ServiceReq_UserAuth
  |`Receive_Transport_Unimplemented
  |`Signal_HUP
  |`Signal_Quit
  |`Transmit_Auth_Banner
  |`Transmit_Auth_ChangeReq
  |`Transmit_Auth_Failure
  |`Transmit_Auth_PublicKey_OK
  |`Transmit_Auth_Req_Host
  |`Transmit_Auth_Req_None
  |`Transmit_Auth_Req_Password_Change
  |`Transmit_Auth_Req_Password_Request
  |`Transmit_Auth_Req_PublicKey_Check
  |`Transmit_Auth_Req_PublicKey_Request
  |`Transmit_Auth_Success
  |`Transmit_Channel_Close
  |`Transmit_Channel_Data
  |`Transmit_Channel_EOF
  |`Transmit_Channel_ExtendedData
  |`Transmit_Channel_Failure
  |`Transmit_Channel_GlobalRequest_CancelTCPForward
  |`Transmit_Channel_GlobalRequest_TCPForward
  |`Transmit_Channel_OpenConfirmation
  |`Transmit_Channel_OpenFailure
  |`Transmit_Channel_Open_DirectTCP
  |`Transmit_Channel_Open_Session
  |`Transmit_Channel_Open_TCPForward
  |`Transmit_Channel_Open_X11
  |`Transmit_Channel_RequestFailure
  |`Transmit_Channel_RequestSuccess
  |`Transmit_Channel_RequestSuccessPort
  |`Transmit_Channel_Request_Exec
  |`Transmit_Channel_Request_ExitStatus
  |`Transmit_Channel_Request_Pty
  |`Transmit_Channel_Request_Shell
  |`Transmit_Channel_Request_X11
  |`Transmit_Channel_Success
  |`Transmit_Channel_WindowAdjust
  |`Transmit_Dhgexsha1_Group
  |`Transmit_Dhgexsha1_Init
  |`Transmit_Dhgexsha1_Reply
  |`Transmit_Dhgexsha1_Request
  |`Transmit_Dhgroupsha1_Init
  |`Transmit_Dhgroupsha1_Reply
  |`Transmit_Transmit_Unimplemented
  |`Transmit_Transport_Debug
  |`Transmit_Transport_Disconnect
  |`Transmit_Transport_Ignore
  |`Transmit_Transport_KexInit
  |`Transmit_Transport_NewKeys
  |`Transmit_Transport_ServiceAccept_Connection
  |`Transmit_Transport_ServiceAccept_UserAuth
  |`Transmit_Transport_ServiceReq_Connection
  |`Transmit_Transport_ServiceReq_UserAuth
  |`Transmit_Transport_Unimplemented
  |`Transmit_Transport_UserAuth_ServiceAccept
]

let string_of_statecall (x:t) = match x with
  |`Expect_DHInit -> "Expect_DHInit"
  |`Expect_Exec_Success -> "Expect_Exec_Success"
  |`Expect_GexInit -> "Expect_GexInit"
  |`Expect_Pty_Success -> "Expect_Pty_Success"
  |`Expect_Shell_Success -> "Expect_Shell_Success"
  |`Notify_Auth_Permanent_Failure -> "Notify_Auth_Permanent_Failure"
  |`Receive_Auth_Banner -> "Receive_Auth_Banner"
  |`Receive_Auth_ChangeReq -> "Receive_Auth_ChangeReq"
  |`Receive_Auth_Failure -> "Receive_Auth_Failure"
  |`Receive_Auth_PublicKey_OK -> "Receive_Auth_PublicKey_OK"
  |`Receive_Auth_Req_Host -> "Receive_Auth_Req_Host"
  |`Receive_Auth_Req_None -> "Receive_Auth_Req_None"
  |`Receive_Auth_Req_Password_Change -> "Receive_Auth_Req_Password_Change"
  |`Receive_Auth_Req_Password_Request -> "Receive_Auth_Req_Password_Request"
  |`Receive_Auth_Req_PublicKey_Check -> "Receive_Auth_Req_PublicKey_Check"
  |`Receive_Auth_Req_PublicKey_Request -> "Receive_Auth_Req_PublicKey_Request"
  |`Receive_Auth_Success -> "Receive_Auth_Success"
  |`Receive_Channel_Close -> "Receive_Channel_Close"
  |`Receive_Channel_Data -> "Receive_Channel_Data"
  |`Receive_Channel_EOF -> "Receive_Channel_EOF"
  |`Receive_Channel_ExtendedData -> "Receive_Channel_ExtendedData"
  |`Receive_Channel_Failure -> "Receive_Channel_Failure"
  |`Receive_Channel_GlobalRequest_CancelTCPForward -> "Receive_Channel_GlobalRequest_CancelTCPForward"
  |`Receive_Channel_GlobalRequest_TCPForward -> "Receive_Channel_GlobalRequest_TCPForward"
  |`Receive_Channel_OpenConfirmation -> "Receive_Channel_OpenConfirmation"
  |`Receive_Channel_OpenFailure -> "Receive_Channel_OpenFailure"
  |`Receive_Channel_Open_DirectTCP -> "Receive_Channel_Open_DirectTCP"
  |`Receive_Channel_Open_Session -> "Receive_Channel_Open_Session"
  |`Receive_Channel_Open_TCPForward -> "Receive_Channel_Open_TCPForward"
  |`Receive_Channel_Open_X11 -> "Receive_Channel_Open_X11"
  |`Receive_Channel_RequestFailure -> "Receive_Channel_RequestFailure"
  |`Receive_Channel_RequestSuccess -> "Receive_Channel_RequestSuccess"
  |`Receive_Channel_RequestSuccessPort -> "Receive_Channel_RequestSuccessPort"
  |`Receive_Channel_Request_Env -> "Receive_Channel_Request_Env"
  |`Receive_Channel_Request_Exec -> "Receive_Channel_Request_Exec"
  |`Receive_Channel_Request_ExitSignal -> "Receive_Channel_Request_ExitSignal"
  |`Receive_Channel_Request_ExitStatus -> "Receive_Channel_Request_ExitStatus"
  |`Receive_Channel_Request_LocalFlowControl -> "Receive_Channel_Request_LocalFlowControl"
  |`Receive_Channel_Request_Pty -> "Receive_Channel_Request_Pty"
  |`Receive_Channel_Request_Shell -> "Receive_Channel_Request_Shell"
  |`Receive_Channel_Request_Signal -> "Receive_Channel_Request_Signal"
  |`Receive_Channel_Request_Subsystem -> "Receive_Channel_Request_Subsystem"
  |`Receive_Channel_Request_WindowChange -> "Receive_Channel_Request_WindowChange"
  |`Receive_Channel_Request_X11 -> "Receive_Channel_Request_X11"
  |`Receive_Channel_Success -> "Receive_Channel_Success"
  |`Receive_Channel_WindowAdjust -> "Receive_Channel_WindowAdjust"
  |`Receive_Dhgexsha1_Group -> "Receive_Dhgexsha1_Group"
  |`Receive_Dhgexsha1_Init -> "Receive_Dhgexsha1_Init"
  |`Receive_Dhgexsha1_Reply -> "Receive_Dhgexsha1_Reply"
  |`Receive_Dhgexsha1_Request -> "Receive_Dhgexsha1_Request"
  |`Receive_Dhgroupsha1_Init -> "Receive_Dhgroupsha1_Init"
  |`Receive_Dhgroupsha1_Reply -> "Receive_Dhgroupsha1_Reply"
  |`Receive_Transport_Debug -> "Receive_Transport_Debug"
  |`Receive_Transport_Disconnect -> "Receive_Transport_Disconnect"
  |`Receive_Transport_Ignore -> "Receive_Transport_Ignore"
  |`Receive_Transport_KexInit -> "Receive_Transport_KexInit"
  |`Receive_Transport_NewKeys -> "Receive_Transport_NewKeys"
  |`Receive_Transport_ServiceAccept_Connection -> "Receive_Transport_ServiceAccept_Connection"
  |`Receive_Transport_ServiceAccept_UserAuth -> "Receive_Transport_ServiceAccept_UserAuth"
  |`Receive_Transport_ServiceReq_Connection -> "Receive_Transport_ServiceReq_Connection"
  |`Receive_Transport_ServiceReq_UserAuth -> "Receive_Transport_ServiceReq_UserAuth"
  |`Receive_Transport_Unimplemented -> "Receive_Transport_Unimplemented"
  |`Signal_HUP -> "Signal_HUP"
  |`Signal_Quit -> "Signal_Quit"
  |`Transmit_Auth_Banner -> "Transmit_Auth_Banner"
  |`Transmit_Auth_ChangeReq -> "Transmit_Auth_ChangeReq"
  |`Transmit_Auth_Failure -> "Transmit_Auth_Failure"
  |`Transmit_Auth_PublicKey_OK -> "Transmit_Auth_PublicKey_OK"
  |`Transmit_Auth_Req_Host -> "Transmit_Auth_Req_Host"
  |`Transmit_Auth_Req_None -> "Transmit_Auth_Req_None"
  |`Transmit_Auth_Req_Password_Change -> "Transmit_Auth_Req_Password_Change"
  |`Transmit_Auth_Req_Password_Request -> "Transmit_Auth_Req_Password_Request"
  |`Transmit_Auth_Req_PublicKey_Check -> "Transmit_Auth_Req_PublicKey_Check"
  |`Transmit_Auth_Req_PublicKey_Request -> "Transmit_Auth_Req_PublicKey_Request"
  |`Transmit_Auth_Success -> "Transmit_Auth_Success"
  |`Transmit_Channel_Close -> "Transmit_Channel_Close"
  |`Transmit_Channel_Data -> "Transmit_Channel_Data"
  |`Transmit_Channel_EOF -> "Transmit_Channel_EOF"
  |`Transmit_Channel_ExtendedData -> "Transmit_Channel_ExtendedData"
  |`Transmit_Channel_Failure -> "Transmit_Channel_Failure"
  |`Transmit_Channel_GlobalRequest_CancelTCPForward -> "Transmit_Channel_GlobalRequest_CancelTCPForward"
  |`Transmit_Channel_GlobalRequest_TCPForward -> "Transmit_Channel_GlobalRequest_TCPForward"
  |`Transmit_Channel_OpenConfirmation -> "Transmit_Channel_OpenConfirmation"
  |`Transmit_Channel_OpenFailure -> "Transmit_Channel_OpenFailure"
  |`Transmit_Channel_Open_DirectTCP -> "Transmit_Channel_Open_DirectTCP"
  |`Transmit_Channel_Open_Session -> "Transmit_Channel_Open_Session"
  |`Transmit_Channel_Open_TCPForward -> "Transmit_Channel_Open_TCPForward"
  |`Transmit_Channel_Open_X11 -> "Transmit_Channel_Open_X11"
  |`Transmit_Channel_RequestFailure -> "Transmit_Channel_RequestFailure"
  |`Transmit_Channel_RequestSuccess -> "Transmit_Channel_RequestSuccess"
  |`Transmit_Channel_RequestSuccessPort -> "Transmit_Channel_RequestSuccessPort"
  |`Transmit_Channel_Request_Exec -> "Transmit_Channel_Request_Exec"
  |`Transmit_Channel_Request_ExitStatus -> "Transmit_Channel_Request_ExitStatus"
  |`Transmit_Channel_Request_Pty -> "Transmit_Channel_Request_Pty"
  |`Transmit_Channel_Request_Shell -> "Transmit_Channel_Request_Shell"
  |`Transmit_Channel_Request_X11 -> "Transmit_Channel_Request_X11"
  |`Transmit_Channel_Success -> "Transmit_Channel_Success"
  |`Transmit_Channel_WindowAdjust -> "Transmit_Channel_WindowAdjust"
  |`Transmit_Dhgexsha1_Group -> "Transmit_Dhgexsha1_Group"
  |`Transmit_Dhgexsha1_Init -> "Transmit_Dhgexsha1_Init"
  |`Transmit_Dhgexsha1_Reply -> "Transmit_Dhgexsha1_Reply"
  |`Transmit_Dhgexsha1_Request -> "Transmit_Dhgexsha1_Request"
  |`Transmit_Dhgroupsha1_Init -> "Transmit_Dhgroupsha1_Init"
  |`Transmit_Dhgroupsha1_Reply -> "Transmit_Dhgroupsha1_Reply"
  |`Transmit_Transmit_Unimplemented -> "Transmit_Transmit_Unimplemented"
  |`Transmit_Transport_Debug -> "Transmit_Transport_Debug"
  |`Transmit_Transport_Disconnect -> "Transmit_Transport_Disconnect"
  |`Transmit_Transport_Ignore -> "Transmit_Transport_Ignore"
  |`Transmit_Transport_KexInit -> "Transmit_Transport_KexInit"
  |`Transmit_Transport_NewKeys -> "Transmit_Transport_NewKeys"
  |`Transmit_Transport_ServiceAccept_Connection -> "Transmit_Transport_ServiceAccept_Connection"
  |`Transmit_Transport_ServiceAccept_UserAuth -> "Transmit_Transport_ServiceAccept_UserAuth"
  |`Transmit_Transport_ServiceReq_Connection -> "Transmit_Transport_ServiceReq_Connection"
  |`Transmit_Transport_ServiceReq_UserAuth -> "Transmit_Transport_ServiceReq_UserAuth"
  |`Transmit_Transport_Unimplemented -> "Transmit_Transport_Unimplemented"
  |`Transmit_Transport_UserAuth_ServiceAccept -> "Transmit_Transport_UserAuth_ServiceAccept"

